---
title: "HubSpot Data Exploration"
output:
  prettydoc::html_pretty:
  theme: cayman
highlight: github
---

```{r libraries}
#Libraries
library(DT)
library(data.table)
library(tidyverse)
```

```{r load_data}
CustomerData= fread(input = "./Data/Hubspot- Customer Data.csv", verbose = FALSE)
SalesData= fread(input = "./Data/Hubspot Sales Data.csv", verbose = FALSE)
SalesRepcostData= fread(input = "./Data/Hubspot- Sales Rep Cost Data.csv", verbose = FALSE)
SalesRepcostData=data.table(SalesRepcostData)
SalesData$Year=as.numeric(substr(SalesData$`Deal Close`,1,4))

## Filter out Japan
SalesData=SalesData[Country!='Japan']
CustomerData=CustomerData[Country!='Japan']
CustomerData=CustomerData[,1:7]
## Filter out year!=2018
SalesData=SalesData[Year==2018,]
##Month
SalesData$Deal_month=as.numeric(substr(SalesData$`Deal Close`,6,8))
## Revenue
SalesData$Revenue=(Endmonth-SalesData$Deal_month+1)*SalesData$MRR


## Categorize CompanySize CustomerData
CustomerData$CompanySize[CustomerData$Employees %in% c("2 to 5","1","2", "4","5")]<-"1 to 5"
CustomerData$CompanySize[CustomerData$Employees %in% c("9","10",'16','18','25','11 to 25','6 to 10')]<-"6 to 25"
CustomerData$CompanySize[CustomerData$Employees %in% c("26 to 50")]<-"26 to 50"
CustomerData$CompanySize[CustomerData$Employees %in% c("51 to 200")]<-"51 to 200"
CustomerData$CompanySize[CustomerData$Employees %in% c("201 to 1000",'201 to 1,000')]<-"201 to 1000"
CustomerData$CompanySize[CustomerData$Employees %in% c("1,001 to 10,000",'1001 to 10000','10,0001 or more')]<-"1000 or more"

## Categorize CompanySize SalesData
SalesData$CompanySize=SalesData$Employees
SalesData$CompanySize[SalesData$Employees %in% c("Undefined")]<-NA
SalesData$CompanySize[SalesData$Employees %in% c("201 to 500",'501 to 1000')]<-"201 to 1000"
SalesData$CompanySize[SalesData$Employees %in% c('1001 or Above')]<-"1000 or more"


## Categorize Industry CustomerData
CustomerData$Industry_New[CustomerData$Industry %in% c("Information Technology and Services","Information Services","Internet", "Computer & Network Security","Telecommunications",'Computer Software','Computer Hardware')]<-"IT, Computer Software & Hardware"
CustomerData$Industry_New[CustomerData$Industry %in% c("Higher Education","Education Management","E-Learning", "Professional Training & Coaching","Primary/Secondary Education",'Printing','Writing and Editing','Translation and Localization')]<-"Education"
CustomerData$Industry_New[CustomerData$Industry %in% c("Insurance","Venture Capital & Private Equity",'Investment Management', "Accounting","Primary/Secondary Education",'Printing','Writing and Editing','Translation and Localization')]<-"Financial Services"
CustomerData$Industry_New[CustomerData$Industry %in% c("Non-Profit Organization Management","Research",'Investment Management', "Accounting","Market Research",'Think Tanks','Executive Office','Legal Services','Law Practice','Human Resources','Staffing and Recruiting','Human Resources/HR','Marketing and Advertising','Public Relations and Communications','Online Media','Events Services')]<-"Management Consulting"
CustomerData$Industry_New[CustomerData$Industry %in% c("Hospitality","Entertainment/Movie Production",'Sports', "Music","Fine Art",'Design','Entertainment','Leisure, Travel & Tourism','Newspapers','Publishing')]<-"Entertainment & Hospitality"
CustomerData$Industry_New[CustomerData$Industry %in% c("Construction","Building Materials",'Architecture & Planning', "Glass, Ceramics & Concrete","Real Estate",'Commercial Real Estate')]<-"Construction & Real Estate"
CustomerData$Industry_New[CustomerData$Industry %in% c("Outsourcing/Offshoring","Warehousing",'Transportation', "Transportation/Trucking/Railroad","Import and Export")]<-"Logistics and Supply Chain"
CustomerData$Industry_New[CustomerData$Industry %in% c("Retail",'Apparel & Fashion', "Consumer Goods","Luxury Goods & Jewelry",'Wholesale','Cosmetics','Wine and Spirits','Furniture','Business Supplies and Equipment','Ranching','Food Production')]<-"Retail & Wholesale"
CustomerData$Industry_New[CustomerData$Industry %in% c("Medical Devices","Health, Wellness and Fitness",'Hospital & Health Care', "Biotechnology","Pharmaceuticals")]<-"Healthcare"
CustomerData$Industry_New[CustomerData$Industry %in% c("Electrical/Electronic Manufacturing",'Consumer Electronics', "Semiconductors","Machinery",'Automotive','Mechanical or Industrial Engineering','Industrial Automation','Aviation & Aerospace')]<-"Electronic Manufacturing & Machinery"
CustomerData$Industry_New[CustomerData$Industry %in% c("Facilities Services",'Civic & Social Organization', "Utilities","Environmental Services",'Individual & Family Services','Testing Laboratories','Renewables & Environment')]<-"Social Services"

## Categorize Industry SalesData
SalesData$Industry_New[SalesData$Industry %in% c("Information Technology and Services","Information Services","Internet", "Computer & Network Security","Telecommunications",'Computer Software','Computer Hardware')]<-"IT, Computer Software & Hardware"
SalesData$Industry_New[SalesData$Industry %in% c("Higher Education","Education Management","E-Learning", "Professional Training & Coaching","Primary/Secondary Education",'Printing','Writing and Editing','Translation and Localization')]<-"Education"
SalesData$Industry_New[SalesData$Industry %in% c("Insurance","Venture Capital & Private Equity",'Investment Management', "Accounting","Primary/Secondary Education",'Printing','Writing and Editing','Translation and Localization')]<-"Financial Services"
SalesData$Industry_New[SalesData$Industry %in% c("Non-Profit Organization Management","Research",'Investment Management', "Accounting","Market Research",'Think Tanks','Executive Office','Legal Services','Law Practice','Human Resources','Staffing and Recruiting','Human Resources/HR','Marketing and Advertising','Public Relations and Communications','Online Media','Events Services')]<-"Management Consulting"
SalesData$Industry_New[SalesData$Industry %in% c("Hospitality","Entertainment/Movie Production",'Sports', "Music","Fine Art",'Design','Entertainment','Leisure, Travel & Tourism','Newspapers','Publishing')]<-"Entertainment & Hospitality"
SalesData$Industry_New[SalesData$Industry %in% c("Construction","Building Materials",'Architecture & Planning', "Glass, Ceramics & Concrete","Real Estate",'Commercial Real Estate')]<-"Construction & Real Estate"
SalesData$Industry_New[SalesData$Industry %in% c("Outsourcing/Offshoring","Warehousing",'Transportation', "Transportation/Trucking/Railroad","Import and Export")]<-"Logistics and Supply Chain"
SalesData$Industry_New[SalesData$Industry %in% c("Retail",'Apparel & Fashion', "Consumer Goods","Luxury Goods & Jewelry",'Wholesale','Cosmetics','Wine and Spirits','Furniture','Business Supplies and Equipment','Ranching','Food Production')]<-"Retail & Wholesale"
SalesData$Industry_New[SalesData$Industry %in% c("Medical Devices","Health, Wellness and Fitness",'Hospital & Health Care', "Biotechnology","Pharmaceuticals")]<-"Healthcare"
SalesData$Industry_New[SalesData$Industry %in% c("Electrical/Electronic Manufacturing",'Consumer Electronics', "Semiconductors","Machinery",'Automotive','Mechanical or Industrial Engineering','Industrial Automation','Aviation & Aerospace')]<-"Electronic Manufacturing & Machinery"
SalesData$Industry_New[SalesData$Industry %in% c("Facilities Services",'Civic & Social Organization', "Utilities","Environmental Services",'Individual & Family Services','Testing Laboratories','Renewables & Environment')]<-"Social Services"

```

```{r constants}
Endmonth=8
INR_to_USD=71.84
BRL_to_USD=4.11
Sale_Rep_number=3
```

```{r summary}
summary(SalesData)
```

```{r LTV:CAC ratio}

#Revenue Retetion Rate
Retention_Rate=1-((CustomerData$`Ending Revenue`/CustomerData$`Starting Revenue`)^Endmonth)
#Revenue
SalesData$Deal_month=as.numeric(substr(SalesData$`Deal Close`,6,8))
SalesData$Revenue=(Endmonth-SalesData$Deal_month+1)*SalesData$MRR
Total_revenue=sum(SalesData$Revenue)
## Cost
Bangalore_repsalary=SalesRepcostData[Location=='Bangalore',]$`Total Compensation`/INR_to_USD
SaoPaolo_repsalary=SalesRepcostData[Location=='Sao Paolo',]$`Total Compensation`/BRL_to_USD
Cost_Sales=Sale_Rep_number*(Bangalore_repsalary+SaoPaolo_repsalary)*(Endmonth/12)
Cost_Market=Cost_Sales/0.8*0.2
Total_cost=Cost_Sales+Cost_Market
# Customer numebr
Customer_number=nrow(CustomerData)
#ARPC
ARPC=Total_revenue/Customer_number
Gross_margin=(Total_revenue-Total_cost)/Total_revenue

LTV=ARPC*Gross_margin/(1-Retention_Rate)
CAC=Total_cost/Customer_number

LTVtoCAC=LTV/CAC
```

```{r Categorize}
# classify scattered point to the employee size of 10 categories:"","less than 6","6 to 10","11 to 25","26 to 50","51 to 200","201 to 1000","1001 to 10000","10,0001 or more","201 to 1,000" 
CustomerData$CompanySize[CustomerData$Employees %in% c("2 to 5","1","2", "4","5")]<-"1-5"
CustomerData$CompanySize[CustomerData$Employees %in% c("9","10",'16','18','25','11 to 25','6 to 10')]<-"6-25"
CustomerData$CompanySize[CustomerData$Employees %in% c("26 to 50")]<-"26-50"
CustomerData$CompanySize[CustomerData$Employees %in% c("51 to 200")]<-"51-200"
CustomerData$CompanySize[CustomerData$Employees %in% c("201 to 1000",'201 to 1,000')]<-"201-1000"
CustomerData$CompanySize[CustomerData$Employees %in% c("1,001 to 10,000",'1001 to 10000','10,0001 or more')]<-"1000 or more"
```

```{r}
CustomerData$LTVtoCAC=LTVtoCAC #adding LTVtoCAC to CustomerData
#summary(model)
fit <- glm(LTVtoCAC ~ 
           factor(Country) + factor(CompanySize)+ factor(Industry_New)+Month+`Starting Revenue`+`Ending Revenue`, data = CustomerData)
summary(fit)
```

time series model
```{r}
#plot the series and visually examine it for any outliers, volatility, or irregularities
library('ggplot2')
library('forecast')
library('tseries')
time_series_data<-CustomerData[,c("LTVtoCAC","Month")]
time_series_data$Date = as.Date(time_series_data$Month)
ggplot(time_series_data, aes(Date, LTVtoCAC)) + geom_line() + scale_x_date('month')  + ylab("ratio of LTV to CAC") + xlab("")
```

```{r}
#R provides a convenient method for removing time series outliers: tsclean() as part of its forecast package. tsclean() identifies and replaces outliers using series smoothing and decomposition.This method is also capable of inputing missing values in the series if there are any.Note that we are using the ts() command to create a time series object to pass to tsclean():
count_ts = ts(time_series_data[,c('Date')])
time_series_data$clean_ratio = tsclean(count_ts)
ggplot() +
  geom_line(data =time_series_data , aes(x = Date, y = clean_ratio)) + ylab('Cleaned Ratio of LTV to CAC')+
  scale_y_continuous()
#plot the clean series using ggplot:
```
```{r}
#The wider the window of the moving average, the smoother original series becomes. We can take weekly or monthly moving average, smoothing the series into something more stable and therefore predictable:
time_series_data$clean_ratio_ma = ma(time_series_data$clean_ratio, order=7) # using the clean count with no outliers
time_series_data$clean_ratio_ma30 = ma(time_series_data$clean_ratio, order=30)
ggplot() +
  geom_line(data = time_series_data, aes(x = Date, y =  clean_ratio, colour = "Counts")) +
  geom_line(data = time_series_data, aes(x = Date, y =  clean_ratio_ma,   colour = "Weekly Moving Average"))  +
  geom_line(data = time_series_data, aes(x = Date, y =  clean_ratio_ma30, colour = "Monthly Moving Average"))  +
  ylab('Ratio')
count_ma = ts(na.omit(time_series_data$clean_ratio_ma), frequency=30)
decomp = stl(count_ma, s.window="periodic")
deseasonal_cnt <- seasadj(decomp)
plot(decomp)
```

```{r}
#The building blocks of a time series analysis are seasonality, trend, and cycle. These intuitive components capture the historical patterns in the series. 
#Seasonal component refers to fluctuations in the data related to calendar cycles.Usually, seasonality is fixed at some number; for instance, quarter or month of the year.Trend component is the overall pattern of the series
#Cycle component consists of decreasing or increasing patterns that are not seasonal. Usually, trend and cycle components are grouped together. Trend-cycle component is estimated using moving averages.
#Finally, part of the series that can't be attributed to seasonal, cycle, or trend components is referred to as residual or error.
#The process of extracting these components is referred to as decomposition.

#First, we calculate seasonal component of the data using stl(). STL is a flexible function for decomposing and forecasting the series. It calculates the seasonal component of the series using smoothing, and adjusts the original series by subtracting seasonality in two simple lines:
count_ma = ts(na.omit(time_series_data$clean_ratio_ma), frequency=30)
decomp = stl(count_ma, s.window="periodic")
deseasonal_cnt <- seasadj(decomp)
plot(decomp)
#now have a de-seasonalized series and can proceed to the next step
```
```{r}
#Fitting an ARIMA model requires the series to be stationary. A series is said to be stationary when its mean, variance, and autocovariance are time invariant.data values oscillate with a steady variance around the mean he augmented Dickey-Fuller (ADF) test is a formal statistical test for stationarity.
# formal ADF test does not reject the null hypothesis of non-stationarity, confirming our visual inspection: 
adf.test(count_ma, alternative = "stationary")
```
```{r}
#Usually, non-stationary series can be corrected by a simple transformation such as differencing. Differencing the series can help in removing its trend or cycles.  Autocorrelation plots (also known as ACF or the auto correlation function) are a useful visual tool in determining whether a series is stationary. 
Acf(count_ma, main='')

Pacf(count_ma, main='')
```

```{r}
count_d1 = diff(deseasonal_cnt, differences = 1)
plot(count_d1)
adf.test(count_d1, alternative = "stationary")
Acf(count_d1, main='ACF for Differenced Series')
Pacf(count_d1, main='PACF for Differenced Series')
```

```{r}
auto.arima(deseasonal_cnt, seasonal=FALSE)
```

```{r}
#Evaluate and Iterate
#We can start by examining ACF and PACF plots for model residuals. If model order parameters and structure are correctly specified, we would expect no significant autocorrelations present. 
fit<-auto.arima(deseasonal_cnt, seasonal=FALSE)
tsdisplay(residuals(fit), lag.max=45, main='(1,1,1) Model Residuals')
```
```{r}
fit2 = arima(deseasonal_cnt, order=c(1,1,6))

fit2

tsdisplay(residuals(fit2), lag.max=15, main='Seasonal Model Residuals')
```

```{r}
fcast <- forecast(fit2, h=30)
plot(fcast)
#The black line above shows the fit provided by the model
```
```{r}
hold <- window(ts(deseasonal_cnt), start=700)

fit_no_holdout = arima(ts(deseasonal_cnt[-c(700:725)]), order=c(1,1,6))

fcast_no_holdout <- forecast(fit_no_holdout,h=25)
plot(fcast_no_holdout, main=" ")
lines(ts(deseasonal_cnt))
```

```{r}
fit_w_seasonality = auto.arima(deseasonal_cnt, seasonal=TRUE)
fit_w_seasonality
seas_fcast <- forecast(fit_w_seasonality, h=30)
plot(seas_fcast)
```

```{r}
# Basic Scatterplot Matrix
pairs(~Starting_Revenue+Ending_Revenue+as.numeric(Month)+LTVtoCAC,data=CustomerData, 
   main="Simple Scatterplot Matrix") 
```

```{r}
scatterplot(LTVtoCAC~ Starting_Revenue | Month, data=mtcars, 
  	xlab="Weight of Car", ylab="Miles Per Gallon", 
   main="Enhanced Scatter Plot", 
   labels=row.names(mtcars))
```

#plot the relationship of starting revenue, ending revenue respectively with Month
```{r}
CustomerData %>%
  select(`Starting Revenue`,Month) %>%
  group_by(Month) %>%
  #summarise(all_starting_revenue = sum(`Starting Revenue`)) %>%
  ggplot(aes(Month,`Starting Revenue`,group = 1)) +
  geom_line() +
  geom_smooth(method = "loess", color = "blue") +
  labs(y = "Starting Revenue", x = "Month")
```

```{r}
library(corrplot)
names(CustomerData)[6]<-"Starting_Revenue"
names(CustomerData)[7]<-"Ending_Revenue"
CustomerData$Month<-as.numeric(CustomerData$Month)
x<-CustomerData[,c("Starting_Revenue", "Ending_Revenue", "Month","LTVtoCAC")]
#x<-lapply(x, as.numeric)
correlations <- cor(x, use = "complete.obs")
corrplot(correlations)
corrplot(correlations, method = "square",type = 'upper')
```

```{r}
CustomerData %>%
  select(`Ending Revenue`,Month) %>%
  group_by(Month) %>%
  #summarise(all_starting_revenue = sum(`Starting Revenue`)) %>%
  ggplot(aes(Month,`Ending Revenue`,group = 1)) +
  geom_line() +
  geom_smooth(method = "loess", color = "blue") +
  labs(y = "Ending Revenue", x = "Month")
```







